[package]
name = "can"
version = "0.1.0"
edition = "2018"

[dependencies]
bxcan = "0.5.0"
embedded-hal = "0.2"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.6"
panic-halt = "0.2"

[dependencies.stm32f4xx-hal]
version = "0.9"
features = ["can", "stm32f429"]
