APPLICATION = spi

BOARD ?= frdm-k64f

RIOTBASE ?= $(CURDIR)/../../../library/RIOT

USEMODULE += periph_spi

DISABLE_MODULE += cortexm_fpu

DEVELHELP ?= 0
QUIET ?= 0

include $(RIOTBASE)/Makefile.include
