APPLICATION = spi

BOARD ?= arduino-due

RIOTBASE ?= $(CURDIR)/../../../library/RIOT

USEMODULE += periph_adc
USEMODULE += periph_dac
USEMODULE += periph_gpio
USEMODULE += periph_pwm
USEMODULE += periph_spi
USEMODULE += periph_timer
USEMODULE += periph_uart

DEVELHELP ?= 1
QUIET ?= 0

include $(RIOTBASE)/Makefile.include
