APPLICATION = spi

BOARD ?= arduino-due

RIOTBASE ?= $(CURDIR)/../../../library/RIOT

USEMODULE += periph_spi
USEMODULE += periph_uart

DEVELHELP ?= 1
QUIET ?= 0

include $(RIOTBASE)/Makefile.include
